##Some useful things for the future:
## st.write_stream for outputting text generated by OpenAI
##
##
import streamlit as st

from streamlit_image_coordinates import streamlit_image_coordinates     ##manually select points for posture evaluation
from streamlit_image_comparison import image_comparison                 ##compare two postures
from streamlit_plotly_events import plotly_events                       ##interactively view data on graphs

import numpy as np
##import openai
import plotly.express as px                                             
import pandas as pd


##temp vars for class or similar
hasAccount = False
dailyPhotoUpload = False


st.set_page_config(
    page_title="Posture Priority",
    page_icon="🚶",
    layout="centered",
    initial_sidebar_state='auto'
)

st.title('Posture Priority')

if not hasAccount:
    st.subheader("Log in or sign up to get started")
elif not dailyPhotoUpload:
    st.subheader("Upload a photo for today")
else:
    st.subheader("Welcome back!")





